version: 2

project_name: cullarr

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/cullarr
    binary: cullarr
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE

checksum:
  name_template: checksums.txt

release:
  github:
    owner: bvdwalt
    name: cullarr

dockers_v2:
  - images:
      - "robotwizard/cullarr"
    tags:
      - "{{ .Version }}"
      - latest
    dockerfile: Dockerfile.goreleaser
    platforms:
      - linux/amd64
      - linux/arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
